/** Mapa de AVL IDs → nombre legible + unidad por defecto. Compartido entre CAN Scanner y editor de sensores. */
export const AVL_NAMES: Record<string, { name: string; unit: string }> = {
  avl_1:   { name: 'DIN 1', unit: '0/1' },
  avl_2:   { name: 'DIN 2', unit: '0/1' },
  avl_3:   { name: 'DIN 3', unit: '0/1' },
  avl_4:   { name: 'DIN 4', unit: '0/1' },
  avl_6:   { name: 'Dallas Temp 5', unit: '°C ×0.1' },
  avl_8:   { name: 'Dallas Temp 6', unit: '°C ×0.1' },
  avl_9:   { name: 'AIN 1', unit: 'V ×0.001' },
  avl_10:  { name: 'AIN 2', unit: 'V ×0.001' },
  avl_11:  { name: 'AIN 3', unit: 'V ×0.001' },
  avl_14:  { name: 'Engine Worktime', unit: 'min' },
  avl_16:  { name: 'Total Mileage (counted)', unit: 'm' },
  avl_17:  { name: 'Fuel Consumed (counted)', unit: 'L ×0.1' },
  avl_18:  { name: 'Fuel Rate', unit: 'L/h ×0.1' },
  avl_19:  { name: 'AdBlue Level', unit: '%' },
  avl_20:  { name: 'AdBlue Level', unit: 'L ×0.1' },
  avl_21:  { name: 'GSM Signal', unit: '0–5' },
  avl_23:  { name: 'Engine Load', unit: '%' },
  avl_24:  { name: 'Speed (CAN)', unit: 'km/h' },
  avl_25:  { name: 'Engine Temp', unit: '°C ×0.1' },
  avl_30:  { name: 'Vehicle Speed', unit: 'km/h' },
  avl_31:  { name: 'Accelerator Pedal', unit: '%' },
  avl_33:  { name: 'Fuel Consumed', unit: 'L ×0.1' },
  avl_34:  { name: 'Fuel Level', unit: 'L ×0.1' },
  avl_35:  { name: 'Engine RPM', unit: 'rpm' },
  avl_36:  { name: 'Total Mileage', unit: 'm' },
  avl_37:  { name: 'Fuel Level', unit: '%' },
  avl_66:  { name: 'External Voltage', unit: 'mV' },
  avl_67:  { name: 'Battery Voltage', unit: 'mV' },
  avl_68:  { name: 'Battery Current', unit: 'mA' },
  avl_70:  { name: 'PCB Temperature', unit: '°C ×0.1' },
  avl_71:  { name: 'GNSS Status', unit: '0–5' },
  avl_72:  { name: 'Dallas Temp 1', unit: '°C ×0.1' },
  avl_73:  { name: 'Dallas Temp 2', unit: '°C ×0.1' },
  avl_74:  { name: 'Dallas Temp 3', unit: '°C ×0.1' },
  avl_75:  { name: 'Dallas Temp 4', unit: '°C ×0.1' },
  avl_78:  { name: 'iButton', unit: '' },
  avl_79:  { name: 'Brake Switch', unit: '0/1' },
  avl_80:  { name: 'Wheel Speed (CAN)', unit: 'km/h' },
  avl_81:  { name: 'Cruise Control', unit: '0/1' },
  avl_82:  { name: 'Clutch Switch', unit: '0/1' },
  avl_83:  { name: 'PTO State (alt)', unit: '0/1' },
  avl_84:  { name: 'Accel. Pedal Pos.', unit: '%' },
  avl_85:  { name: 'Engine Load', unit: '%' },
  avl_86:  { name: 'Total Fuel Used', unit: 'L' },
  avl_87:  { name: 'Fuel Level (J1939)', unit: '%' },
  avl_88:  { name: 'Engine RPM (J1939)', unit: 'rpm' },
  avl_104: { name: 'Engine Hours', unit: 'h' },
  avl_113: { name: 'Service Distance', unit: 'km' },
  avl_127: { name: 'Coolant Temp', unit: '°C' },
  avl_135: { name: 'Fuel Rate (J1939)', unit: 'L/h' },
  avl_139: { name: 'Gross Weight', unit: 'kg' },
  avl_176: { name: 'DTC Errors Count', unit: '' },
  avl_179: { name: 'PTO State', unit: '0/1' },
  avl_180: { name: 'Digital Output 2', unit: '0/1' },
  avl_181: { name: 'GNSS PDOP', unit: '×0.1' },
  avl_182: { name: 'GNSS HDOP', unit: '×0.1' },
  avl_199: { name: 'Trip Odometer', unit: 'm' },
  avl_200: { name: 'Sleep Mode', unit: '' },
  avl_205: { name: 'GSM Cell ID', unit: '' },
  avl_206: { name: 'GSM Area Code', unit: '' },
  avl_239: { name: 'Ignition', unit: '0/1' },
  avl_240: { name: 'Movement', unit: '0/1' },
  avl_245: { name: 'AIN 4', unit: 'V ×0.001' },
  // Manual CAN slots 0–9 → AVL 145–154
  avl_145: { name: 'CAN Manual 0', unit: '' },
  avl_146: { name: 'CAN Manual 1', unit: '' },
  avl_147: { name: 'CAN Manual 2', unit: '' },
  avl_148: { name: 'CAN Manual 3', unit: '' },
  avl_149: { name: 'CAN Manual 4', unit: '' },
  avl_150: { name: 'CAN Manual 5', unit: '' },
  avl_151: { name: 'CAN Manual 6', unit: '' },
  avl_152: { name: 'CAN Manual 7', unit: '' },
  avl_153: { name: 'CAN Manual 8', unit: '' },
  avl_154: { name: 'CAN Manual 9', unit: '' },
  // Manual CAN slots 10–19 → AVL 380–389
  avl_380: { name: 'CAN Manual 10', unit: '' },
  avl_381: { name: 'CAN Manual 11', unit: '' },
  avl_382: { name: 'CAN Manual 12', unit: '' },
  avl_383: { name: 'CAN Manual 13', unit: '' },
  avl_384: { name: 'CAN Manual 14', unit: '' },
  avl_385: { name: 'CAN Manual 15', unit: '' },
  avl_386: { name: 'CAN Manual 16', unit: '' },
  avl_387: { name: 'CAN Manual 17', unit: '' },
  avl_388: { name: 'CAN Manual 18', unit: '' },
  avl_389: { name: 'CAN Manual 19', unit: '' },
}

/** Lista ordenada de AVL IDs para selectores UI. */
export const AVL_OPTIONS = Object.entries(AVL_NAMES)
  .map(([key, info]) => ({ id: parseInt(key.replace('avl_', '')), name: info.name, unit: info.unit }))
  .sort((a, b) => a.id - b.id)
